os: linux
language: ruby
sudo: required
before_install: 
- sudo apt-get install ruby
- gem install sinatra
- gem install json
- gem install activesupport
- gem install net
- gem install travis
- ruby ./travis.rb

script: 
- curl -o pulls.html https://api.github.com/repos/DengShuaiSimon/xcat-core/pulls
- cd ..
- cd ..
- ls -a
- pwd
- cd ..
- ls -a
#- cat build.sh
- cd build
- pwd
- ls -a
- cd ..
#- cat .travis_ci_environment.yml
#- cat .travis_packer_templates_rspec.json
- cd builds
- pwd
- ls -a
- cd ..
- cd .travis
- ls -a
- cd job_stages
- ls -a
- cat job_stages
