os: linux
language: ruby
sudo: required
before_install: 
- sudo apt-get install ruby
- gem install sinatra
- gem install json
- gem install activesupport
- gem install net
#- gem install travis
- ruby ./travis.rb

script: 
- curl -o pulls.html https://api.github.com/repos/DengShuaiSimon/TravisTest/events
- cd ..
- cd ..
- ls -a
- pwd
- cd ..
- ls -a
#- cat build.sh
#- cd build
- pwd
#- ls -a
- cd ..
##- cat .travis_ci_environment.yml
##- cat .travis_packer_templates_rspec.json
#- cd builds
- pwd
- ls -a
- cd ..
- cd .travis
#- ls -a
- cat job_stages
- echo $TRAVIS_BUILD_ID
- echo $TRAVIS_EVENT_TYPE
- echo $TRAVIS_BUILD_NUMBER
- echo $TRAVIS_BUILD_DIR
- echo $TRAVIS_COMMIT
- echo $TRAVIS_COMMIT_MESSAGE
- echo $TRAVIS_COMMIT_RANGE
- echo $TRAVIS_JOB_ID
- echo $TRAVIS_JOB_NUMBER
- echo $TRAVIS_BRANCH
- echo $TRAVIS_COMMIT_MESSAGE
- git log --format=%B -n 2
#- curl -i https://api.github.com/repos/DengShuaiSimon/TravisTest/issues/9/comments
- git log --pretty=format:"%s %b" -2
- git log --pretty=format:"%s" -1
- git log --pretty=format:"%b" -1
- git log --format=%s -n 3
- git log --format=%B -n 3
